// <auto-generated />
using System;
using IVnews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IVnews.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006225225_ConfiguraCategoriaOutros")]
    partial class ConfiguraCategoriaOutros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("IVnews.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdExterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Notícias sobre política nacional e internacional",
                            Nome = "Política"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Notícias sobre esportes em geral",
                            Nome = "Esporte"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Notícias sobre tecnologia e inovação",
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Notícias sobre saúde e bem-estar",
                            Nome = "Saúde"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Notícias sobre economia e mercado financeiro",
                            Nome = "Economia"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Notícias sobre categorias variadas",
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("IVnews.Model.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Localizacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Maringá",
                            Estado = "PR",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "São Paulo",
                            Estado = "SP",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Curitiba",
                            Estado = "PR",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Rio de Janeiro",
                            Estado = "RJ",
                            Pais = "Brasil"
                        });
                });

            modelBuilder.Entity("IVnews.Model.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdExterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalizacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublicadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlNoticia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("IVnews.Model.Resumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoticiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoticiaId");

                    b.ToTable("Resumos");
                });

            modelBuilder.Entity("IVnews.Model.Noticia", b =>
                {
                    b.HasOne("IVnews.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("IVnews.Model.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId");

                    b.Navigation("Categoria");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("IVnews.Model.Resumo", b =>
                {
                    b.HasOne("IVnews.Model.Noticia", "Noticia")
                        .WithMany()
                        .HasForeignKey("NoticiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
