// <auto-generated />
using System;
using IVnews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IVnews.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907142613_ExpandeCamposNoticiaCategoriaLocalizacao")]
    partial class ExpandeCamposNoticiaCategoriaLocalizacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("IVnews.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Notícias sobre política nacional e internacional",
                            Nome = "Política"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Notícias sobre esportes em geral",
                            Nome = "Esporte"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Notícias sobre tecnologia e inovação",
                            Nome = "Tecnologia"
                        });
                });

            modelBuilder.Entity("IVnews.Model.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Localizacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Maringá",
                            Estado = "PR",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "São Paulo",
                            Estado = "SP",
                            Pais = "Brasil"
                        });
                });

            modelBuilder.Entity("IVnews.Model.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalizacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublicadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("Noticias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Redação IV News",
                            CategoriaId = 3,
                            Conteudo = "Conteúdo de exemplo pra testar o banco.",
                            Fonte = "IV News",
                            ImagemUrl = "https://via.placeholder.com/600x400",
                            LocalizacaoId = 1,
                            PublicadoEm = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Notícia de teste"
                        });
                });

            modelBuilder.Entity("IVnews.Model.Resumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoticiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoticiaId");

                    b.ToTable("Resumos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NoticiaId = 1,
                            Texto = "Resumo de exemplo da notícia de teste."
                        });
                });

            modelBuilder.Entity("IVnews.Model.Noticia", b =>
                {
                    b.HasOne("IVnews.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IVnews.Model.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("IVnews.Model.Resumo", b =>
                {
                    b.HasOne("IVnews.Model.Noticia", "Noticia")
                        .WithMany()
                        .HasForeignKey("NoticiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
